
datasets ,= glob_wildcards("input/{dataset}.fasta")
genomes ,= glob_wildcards("genomes/{genome}.fna")

genes = {
    'nifH': [ "reviewed:true", "xref:interpro-IPR005977", "taxonomy_id:1117" ],
    'GvTcR': [ "accession:Q7NKP0" ]
}

databases, bases ,= glob_wildcards("databases/{database}/{base}.fna.ndb")

profile = 'PF01036'

include: "Cyanobacterial_clade.snakefile"
include: "Cyanobacterial_XR_genomes.snakefile"
include: "Global_XR_phylogeny.snakefile"
include: "Rhodopsins_in_cyanobacteria.snakefile"

rule all:
    input:
        "output/Cyanobacterial_XR_clade.svg",
        "output/All_prokaryotic_XRs.svg",
        expand("output/Rhodopsins_in_cyanobacteria_{database}-{base}.svg", zip, database = databases, base = bases)

# Make blast database for a protein fasta
rule makeblast_prot:
    input:
        "{prefix}.faa"
    output:
        "{prefix}.faa.pdb"
    conda:
        "envs/search.yaml"
    shell:
        "makeblastdb -in {input} -dbtype prot"

# Download Pfam profile
rule dload_pfam:
    output:
        "analysis/pfam/{profile}.hmm"
    params:
        url = "https://www.ebi.ac.uk/interpro/wwwapi/entry/pfam/{profile}?annotation=hmm"
    shell:
        "wget -O- {params.url:q} | gzip -cd > {output}"

# Copy the rhodopsin list (rhodopsins from families present in prokaryotes)
rule copy_rhodopsin_list:
    input:
        "databases/Rhodopsin_list.faa"
    output:
        "analysis/rhodopsin_list/Rhodopsin_list.faa"
    shell:
        "cp {input} {output}"
